Upgrade uniswapv2
scroll-tech/trace-dumper pull request #17
Opened 2023-05-31 08:43 UTC by mask-pp

2023-05-31 15:01 UTC, HAOYUatHZ requested changes

2023-05-31 15:01 UTC, HAOYUatHZ commented on docker/l2geth/Dockerfile
> +FROM scrolltech/l2geth:scroll-v3.1.12
we want to use `scroll-v3.3.1`

2023-06-01 01:19 UTC, mask-pp commented on docker/l2geth/Dockerfile
> +FROM scrolltech/l2geth:scroll-v3.1.12
changed.

2023-06-01 03:15 UTC, 29988122 approved these changes, later dismissed

2023-06-05 01:12 UTC, HAOYUatHZ commented on Makefile
> +	docker build --no-cache -t trace-dumper ./docker/l2geth/.
```suggestion
	docker build --no-cache -t trace-dumper/l2geth ./docker/l2geth/.
```

2023-06-05 01:38 UTC, HAOYUatHZ approved these changes

2023-06-05 01:39 UTC, merged